### ISSUE TITLE
Could you explain why use distance as the weight?

### ISSUE THREAD

**Issue by perfecthu** [zhly0/facenet-face-cluster-chinese-whispers-#6]
It is really confusing that using distance as the weight. Base on my understanding, the weight should be positively correlated with the similarity. However, the distance is negatively correlated with similarity. Could you please provide some explanation?

**Comment by huan** [comment]
+1

I have the same question.

**Comment by zhly0** [comment]
The distance is used as the weights,so no matter use 1-distance or distance as weights,the same class should be in the same cluster center,and it is somehow related to the distance you choose,if you choose cosin distance,then the distance is positively correlated with similarity,if you choose the distance in the code,then it is negatively correlated with similarity.And both should work,but the result may not be the same.you can try different measurements and use the best one.

**Comment by zhly0** [comment]
If you want to know the details of the algorithm,you can refer to paper:Chinese Whispers- an Efficient Graph Clustering Algorithm and its Applications to Natural Language Processing Problems.The paper should give you detail.

**Comment by huan** [comment]
@zhly0 I don't think so.

https://github.com/zhly0/facenet-face-cluster-chinese-whispers-/blob/9a4b74350f05c59cf23a75279cfb4a6906db91da/facenet_face_cluster.py#L106-L110

According to the above code, you assigned the class(file path) of max "weight" to the current node, which your "weight" is not the real ~weight~, but a _distance_.

So I believe the result of this code snip has a bug: it should use the `1/distance` as the weight, instead of use distance itself.

I had implemented a Chinese Whispers Algorithm in Node.js at here: https://github.com/zixia/chinese-whispers, please correct me if I'm wrong, thank you!

**Comment by huyingxi** [comment]
我也有同样的疑问，为什么cosin distance和euclidean distance都可以作为边的权值呢？

**Comment by zhly0** [comment]
@zixia @huyingxi  sorry,there is something wrong in my description.both cosin distance and euclidean distance can be use as weights(graph edges),but if use  cosin distance,you should use 1-cosin_distance as weights.The idea is that vector from the same person will be close to each other,while different people far apart.If you want to use chinese whisper for face cluster,you have to create a graph of connected faces since the chinese whisper cluster algorithm is based on graph.so if you do not choose distance as weight,what can you choose?as for @zixia ,the code you mentioned is used to find the cluster center,not a  bug.in code line 74:            if distance < threshold:
has already filter the face that not so similar.

**Comment by huan** [comment]
> code line 74: if distance < threshold: has already filtered the face that not so similar.

Yes, I saw it. This line only filtered out all the face that not familiar with the current one, which means only keep the one that distance less than 0.74.

> for @zixia, the code you mentioned is used to find the cluster center, not a bug.

As my understanding, the cluster center should be the minimum distance to the other nodes, which should `minimize(sum(distance))` instead of `maximum(sum(distance))`?

**Comment by zhly0** [comment]
@zixia sorry I do not have much time for go into the code  since I have other stuff at hand,when I have time I will take a detailed look at code

**Comment by zhly0** [comment]
@zixia I look into to the code,and I think the clustering result is rely on these:
1 the threshold you choose,and the deep learning model you choose,the model and the threshold will have a decisive influence on your finall result
2 the iteration in the code to find the maximum sum of the same class,since it is maximum sum of weights in the same class,then the more similar the bigger the weights,so the distance should be 1/distance if you choose  euclidean distance(which you are right,it is a bug!),and use original distance as weights if you choose cosin distance as weights,
now the code use cosin distance,and use if distance > threshold: in line 75
thanks for correcting me!

**Comment by huan** [comment]
Glad to hear from you again, and thank you for the confirmation.

I need the confirmation because I'm using 1/distance(from facenet) in my ChineseWhispers module, so we are all good now. 

Cheers!
